export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none
  --color=bg+:#2b2b30 \
  --color=bg:#020202 \
  --color=border:#6a6a6c \
  --color=fg:#ffffff \
  --color=gutter:#020202 \
  --color=header:#ffa56e \
  --color=hl+:#9ff5ff \
  --color=hl:#9ff5ff \
  --color=info:#565660 \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#9ff5ff \
  --color=query:#ffffff:regular \
  --color=scrollbar:#6a6a6c \
  --color=separator:#ffa56e \
  --color=spinner:#ff007c \
"
